spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(KUJNgDMlvi/imeVHjCO2QekgI4DNxZT9IrW0QlVVkJXJUUQ2DAUOqI91FVH7aFhXVCsfXtf0EUmF/JqN3GpXa/mVj3o4BNbqS3QsU50BgwEEodko+VwHY2ebDHUxlKA1/FXBSmu6p+Rd3rcNEzoBIA==)
      username: ENC(s3n0zgMcVpi2eYZp1Iqbfg==)
      password: ENC(VRtr3RjM+XnPvRdLjrPMHyTSzDlEjR7o)
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(KUJNgDMlvi/imeVHjCO2QekgI4DNxZT9IrW0QlVVkJXJUUQ2DAUOqI91FVH7aFhXVCsfXtf0EUmF/JqN3GpXa/mVj3o4BNbqS3QsU50BgwEEodko+VwHY2ebDHUxlKA1/FXBSmu6p+Rd3rcNEzoBIA==)
      username: ENC(s3n0zgMcVpi2eYZp1Iqbfg==)
      password: ENC(VRtr3RjM+XnPvRdLjrPMHyTSzDlEjR7o)
  flyway:
    baseline-version: 2
    
log:
  file:
    path: /ody-prod-logs
