services:
  db:
    image: mysql:8.0.35
    container_name: mysql-local-db
    restart: always
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ody
      TZ: Asia/seoul

  redis:
    image: redis:7.4.1-alpine3.20
    container_name: redis-local
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --save "" 
      --appendonly yes
      --auto-aof-rewrite-percentage 0
    environment:
      TZ: Asia/Seoul

  redis2:
    image: redis:7.4.1-alpine3.20
    container_name: redis-local-lettuce
    restart: always
    ports:
      - "6380:6379"
    command: >
      redis-server 
      --save "" 
      --appendonly yes
      --auto-aof-rewrite-percentage 0
      --notify-keyspace-events Ex
    environment:
      TZ: Asia/Seoul
