spring:
  config:
    import: classpath:private/private.yml
  profiles:
    default: "local"
    groups:
      local:
        - local
        - common
      dev:
        - dev
        - common
      prod:
        - prod
        - common
