spring:
  config:
    import: classpath:private/private.yml, classpath:common.yml
  profiles:
    default: "local"
    groups:
      local:
        - local
      dev:
        - dev
      prod:
        - prod
