spring:
  data:
    redis:
      host: ENC(F7JRlpyJcHS5td+d3+T79m9aK+lIabNw)
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(kbgu5EFSNExIBz2TI97Ouu84x1+1srF7obAjVZkLNS1qGyfnud0rRHYEdwWBGgbx0+OmsgcLWGlc92SgsTZsSB7MM2Hl29Sg76UzZOFT0hQfZVgP7kcCPOwU4pDX3QInuuYbl47CJjs=)
      username: ENC(hUSFqr+kl28AIVDKBfyRHA==)
      password: ENC(yjnFbKAlVVvzzQuWNECa7DcpWubhBn0Q)
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(kbgu5EFSNExIBz2TI97Ouu84x1+1srF7obAjVZkLNS1qGyfnud0rRHYEdwWBGgbx0+OmsgcLWGlc92SgsTZsSB7MM2Hl29Sg76UzZOFT0hQfZVgP7kcCPOwU4pDX3QInuuYbl47CJjs=)
      username: ENC(hUSFqr+kl28AIVDKBfyRHA==)
      password: ENC(yjnFbKAlVVvzzQuWNECa7DcpWubhBn0Q)
  flyway:
    baseline-version: 1

log:
  file:
    path: /ody-prod-logs
