spring:
  jpa:
    open-in-view: false
    defer-datasource-initialization: false
  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    enabled: true

odsay:
  url: https://api.odsay.com/v1/api/searchPubTransPathT
  api-key: ENC(4+ag02XbL8zS6rWoWHh7WzhKqBj5kaBwBcg04MpLr8nLJefO2PRY8E5o0WpRd3oRtvFv1s9lnWI=)
  # TODO: 임시로 개인 api-key 추가 -> 팀 key로 변경 필요

google:
  maps:
    api-key: ENC(ISqnJHlmWWslx8mw0KghjXcJsTcxZ97AoylekuQiZN3RGyolV7oejAM3ejRtUllp)

auth:
  access-key: ENC(jp1TJCM6l22zIzInTUvt9VXrb1WhNm1zY3dFgTSj6ad3585f5K7Q8A==)
  access-expiration: ENC(RA/POzGT/Baq/ba9MxmMAQ==)
  refresh-key: ENC(5uLKuwtNdyXnr61LRqQJ6Q2sfbhjW5vxgLADB4Na8YgoIkLvcmJk+A==)
  refresh-expiration: ENC(LUMzldRJndHMoxKs+pyCF5J0MrT94NY+)

fcm:
  config:
    admin-sdk: ENC(ABeTi+aVwqfh9ZhYEuAg8bIAxJewup2AQ2AKxAfLYFY443VUoByvQb7MsAp0kdQTNSgEaIvcKwVf8LaPjws9R9GhJt+sSA6G8SiuidxYB7A54GJfOAbwxkoxRqM8uCCiI8m3FTJrbt4Kr4ZGxQ4EcYQZDkZvK7vFd2LNFvPyDuHCPkEA7QD1+QbLPIUjOcyUQ8LwDTKk7N5hRt2EOC+XrwbEvxB0CIGmau36bkQ40yaL8ZNlW8ulrvm/jxPSRrY1NqcSe5Gm0Ue8qm5ANweNN/AE53zUVu3IWbW/+O1Cm03+qI+KLQppJJOcn8IVNbgourH5+3BOwvESoHwhVnGaMswY3n6jD+xHVV5BFzanfWCGHEm+2f3H7Mun2s8ACfW2J0kPWEA+yY2u2i6n7LNQLs+PDwp81omUppY20D/QWa3rzmtKA7813ZUlc7objNkdz2HdRp+EiZXufZEP0hYkf3bs1OApJmKMVnqYffz+wZlbrxAv0SgUxdrat5Zp4vDY5B0NsbtwA79jT0kNqu66wlP8wbhK7DxzDOA6vi568UR7DmEjwa2CFDqW070diCewgSWXCCDQOFMWZ1rxOrt3vR8QLU/CndmajkVrc1zOUj1ikEVFfrRS2g1YESNxLFkSMYFxA8RxIefP9aQcbZlRMAmyPzQP2J96AlA0YwFxzK/gHvlUXXKDB3062RlN/krSuYdbUO01OiuecB5TW+DTvktcBD32m+8f7r/nalN9jsSrel5J3DORNkPoRaoZNaksC629L7Ym3ZN9mEueGAiiq34DtoZslhjrqm88nAXYEyLFASxGbr7KYjWuoiCRXhkS0X45/x7Esjt5LVrgfKxp5AjgwEeSK+tP18up9+jZv7+BMoQSzful+5IHKquelB2irZnc0kPD8xK9VmhEqyoGS9oTEsvjI94Ts87Kh1b7IHkP/SHw0yxuV/AV8UP9bnyRAVF2ZXYZo/hJLJ/1x1m25tkDh53/KLm5PtdWOvtFTbUsYBf/cG5QQMFvsV08FhSHT0zmfL8SMkP049ZARwFItjkpZU828GHzLSWpRXeZi0qnASlt9MBJdaq/Uc7Ed6Ssr9H9QEa6PPFqBIM1zobua9iy65v9bxIHIWe4TNvZpUNzOt9nFX6m+Px3rW4tpvqKKWrnvKDExyIzDejbAIv2pOKpHS9sY4QV6BSfpMHG8vbr9QNYrvkWxP8aorurRZBBGYGBMBqyBFQ4ClCHPR+xbSiHo2JX4WUQepbXX/FyhF3zn5Y03Dh8o/L7Wkj9HSWuRVBQvfHRiiLbi8ILfQ2tQ6PjVo/gdI1634ZFYc3mlkJyNz8sR3if3OLgHdEiKg3869pgDovbPM0eJ/rvhoeLSji/lJtsPBsc7/2r6CERsgj5NSqj8jv2IsrhWsrdB72eh10ZZQI6ps58kBXPWOwe/nypiAbWiWtHS1Gopls1RacWGpeznehDpLDdODgAnRD03rY42PxFu9NPmNFy9aBvHeofeHyKLI3PNSWzcOjY4AyC/ptBjqHsxZTvm64QYPY93W0xuIHIoYIyj2G738Y1vCEm0259l4snKFJYLdoPjwou9FY1hYAazn+QgGTO9c0SfhW+YLMvAMi/YDM/g4cQO5R4/V9xqFnmE+SArXLMGVVLDsAfW7ec+W3Kt/lD2gvkhDMM0KE+mEbNrbuTdiknhmDaHGQ97L4UM6bBy6M9WYSvmDHJmpGtUNKCbqKGtUeHN/Pl2j6YENcEWtrbMUDM9UsMYXk6CrrRnQc87uNl6L3kymOC83tl4CYtGTmv3xoQ+JJCsV5OPq05/8Hahblk08zTEYOIqawz6w0TEA5KQiD4YtTrXdCiDPve9jexg0JD27J/sx2s5zwOhpAI48dUnMCAdI9lszLBR6crzvyymisU2HVOAwba03cy7e/z5ThMWG+oyE80AJfr+eUx+26MsHPawvF2ZEWxBrn+wBKDviRbhnTPo49bAJQyu2JuD9Y3rNgPBvz1E5ttriQSXDdnaum43O4l07i/cn1aWC2x8a42CMmofadMVShEDjjoKZR64AHvCWDhNA1mt9SoYQByEKnWoTTdOBZQb1Iz8SESRRiRYaME52gKv5zuyZPM+FkvgPIdTdDht6VrIT265qkzGyO8nWG9KULIoNR1tIweVtzXDeeqXgwkDjzSub0TOb9BkHyXlfL9wpucOZOQtsWVHrCllG9eqOBLJXs6/27k+mMI9pu9AdNA8wdD218Mxz27SZV1Rb4Eex3Gj+/Iyr2mzmRX6tm/HVfkfx/ZV5ZEFOw7U8H8cndSMWT1A7A6KevXo6nwYwYEIYQj+eNL55KRGdtOdRZ8u2B5MojvJBdbTm70ThoDGcjQ4sA7aLD3xOf1+CQ7GASPdUH7lXYOoscbOAKVzuaoxAYP7vWIR/iDPaFnZ3jJfzVlRw/J1ZRRLnAfK0hbmI3gUxe22Y2GS3PG1U4iDyv9jJNIarB6ivmFmwTqJb2nxqQjn5EnQ8mUg7VzAnziPGOB12Ww5Fk46SjgjROJe4gUpVmzzt0+E5fd4Txc48XcKSHGai5hrPC2JJjJ91Sz7xr+KcwuJMDu6j34MuD3yawHlmtRbVbv6HALLZJdyy9figYTnOrFYIUnH8y+4a+P0xYy9oHKrtQBCAkUfXFEXCF9U3Csy3PvbAiTqIYVVjZ8iQ8e4Txkagy73pYHXjfh1NcavmY7G0LkJ/9HV4Ank+VzIYVO7fRWUnDB6J8vcgx/++wnIU1CR+kY6jlhFFM066j60aEw13O/WUVVfpnfxaH4SofKuY53g5zX0Y8WbU83ClcgcKJ60/U4b5vGqJi210fEo3OGNctHi51enSf3QM9HPFXCKUt4zLW001KEKpueFrQ0C4zyRgxcyWPFZXqduCQ5N9nADN9lOcOjeOcYYnNCbhfD69wPVxch507boOxJrxw4ytjLIq29YlFRsC0ZQDuFKawkoqrUuq9wJQf15XMp5jbrjDX42E4+ld6jkxGcYSnUTb/GO/Q1qZain1+WT03nWYPKIOfbCvfN6s234R+1JGKGu8UVCT/mFl5LX6+FUv3UmwGaiZXRxylR92egeyZToaGbHAW2bYOeqNDyKSlAXoBmJNtr1sLNFxNOpQHUOYcdIftE3TETZe93zeYzSAJYEHPoUYReECGXQho6UnU3eMNOwzmawpfEfuSUVfalowcyciCFeBebqpqJ)

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

kakao:
  url: https://kapi.kakao.com/v1/user/unlink
  admin-key: ENC(b8lXOQquegCbdIgayVYIDBrhkNeyuucBArJScDGtEA2IWFiWeGUViiDhyZg0XpFE)

management:
  health:
    db:
      enabled: false
