spring:
  jpa:
    open-in-view: false

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    enabled: true

odsay:
  url: https://api.odsay.com/v1/api/searchPubTransPathT
  api-key: ENC(tHrCTqN0WANDzm2bOdUftqRCbiz64bAyY48Q3FsvMfhRNAnAbpAru/ebTLbwXoDfIcZuSPUFczw=)
  # TODO: 임시로 개인 api-key 추가 -> 팀 key로 변경 필요

auth:
  access-key: ENC(jp1TJCM6l22zIzInTUvt9VXrb1WhNm1zY3dFgTSj6ad3585f5K7Q8A==)
  access-expiration: ENC(RA/POzGT/Baq/ba9MxmMAQ==)
  refresh-key: ENC(5uLKuwtNdyXnr61LRqQJ6Q2sfbhjW5vxgLADB4Na8YgoIkLvcmJk+A==)
  refresh-expiration: ENC(LUMzldRJndHMoxKs+pyCF5J0MrT94NY+)

fcm:
  config:
    admin-sdk: ENC(zZ1dY9ukEcGgAXSp9aOs/EHj85zAzUAEiLECeuvLGBYj/vLtoxfD3JdOhc98lFbSvtlvrhsukFEOQ55cw+geGmyZXcQ5kGKAuQV+fnSBmqJLyWGtXGc4kgtOEqu7PN06JKXGRrg+jSguu95IMbhx2HVFEEVP8bkf6pmW7QyvjQFyQM1f770bn+kS1701tKr/QAtfSWTwA2KMTajNUs6pME9M2QynVgXlgZ2fcFzPKdt0dH5l/suhKlwpFUqUy2B1SGgc4RQP6GxyMkMex0iFYn06L9MeWYyLvURbw3qY1ozc4InoYHrcXlXXJmk/KPCK3JbYbBt9ek6B47X/2W2Zdp4z9ouPKGPd18+/b9eLd+Qme+noFb7koQQOMn6+RkjhThij66W8MD+Vd/gdy6dxbUaqig0zeAzEXeiZQ3GI/Or0ltg1s2/VQ+QVXSimkzMsDJl0zkMcLAU+rab3c3lmRBNlOCCbS3rz+Pqw7vR4Iyrm+HiBkqPHaJgYQCbiWy4EDRAJEhDHXr/uPYPAs/bXgINjf84hR1z85Vr+MrIXY98S4QqcLNDhjiKuR/i/r6HpRSt+7wdEdLuKUayoQjmOvc8G03EncIHxyB4iFipKQj1+euGaw/BDGrztBIZia+bJOI7imPkzSwA972ctFOMr8tiofyHEf+CQEQrjbyMl9dxt2kr/crXi8b6kKbsQ2yuueFAbA21gmUy9TAJzLjJcrTDrcgyiHsMkL+QamTyENr905y27SZEW2sniuXjCN8GtshVnceQI9IzGLX7b7bmn3Y7skP0eIpVAk6M8epAYQxfmhB7zGI/7zT9lXuvD2aJsuFvfkKJlk9SlPglRVtU1gXnQWCAoiGBvOZdIdqDEI8h3eFGlf0FWFjEU03ntCWbHD/VtWArCaikivigI2rdKy7Uw5xyOoM7MENgMcdhry1PbKUg8DPDQQSEo9N624I+g68YoqL/GVXiFVBgw8hgNIwJaGI+zeGT9jCuw7QTk+FULO9eop9J8jRBjgNgiK43eTwfECLVDv2P5g4B0ngLakBOgJ//ZfaVwy10D87zgZZnvDj7FdqjSAlx+6zjLHMXXqM1wRuu1U2ooxRy31mzeQCzCdfSTsUWPh/hrr+sFK5RqQRGT/naMP9M3Odde4sa1RleP5BwtxdexHRYWc3s/2BK1N2BolxcGnjVpU+2E3c98Wco05TLGIsgncIsZDMKjVNVEaDMaOPKruiT9R9nZjUsQAtfh5ELC/uQmQNWvLiVuHBe/8GGjxwLW92/c+TxGEJdq3yPGn/EIL8faZoOABILu4HN3Bb2US5mkrpmbKiW5paeGJB+i5FL31f0GSkcCP+D1aLY00kKyE7lAkwewSnHcE+7+lMAXwmo08CxA7FxNKy21cOn7tSPJK7PsFxR6j+KwUz6T73DGZ5z8t65v/kKan6ICPQxmkCPU/mu6V6zmHDZqDUfQoWC/gnpno1Y7/IZWivOtlaSrSa5JioxMqQj6dJVPNN//kUZ2zt00fLdv3IapTNyoYMhTeq5W8bOLl1fccDIzOKNjn8DQJijQGqd54j+k0pY1zvm7e8qzpdjJPWgJ2/hPrR4EK3biQKDHbegP+ZJhBm+2q8SzOkLU2s4tE9FSM1wtdbXEKPGQZBrfqSuwoAYAuyXLB4Gx+uM88dmpwe8v5ZoKWtOCMFm+UcPUBhv/DMwK5C0dHQnBz+FqxnrgVY6wOm9o8kRINHRg1a0PvVoz6/hg/THIxM7EZ8KMUYf3xlcTralkIFvE82v7vRY6MeuUs+6QWV5sHl1D2ljk84QmMoauywF2EFNMxO2nmJfG5LC2TKe4axF2tQFAZAgUWhKUnMnVJynGTGESsJJHVHz5iVTm8W3hQPcPuHRpHnmDqu5hiRDCthPOONWC/oQSqqL71S5E98L8EIn79bbdiFfOjLpLQaFgFJ9YhcF/Zj1zabJ56b8oWpT5atznBQamyFW3VM9A7pE0zomQ9sPXPD8+NfjKoDzyDFc0lSpB/JJ8Ueb7L38ae2t93CJQjUCpAErRdkfE5W9YUEYiaRDjcLAgvdcBfGcvVwO9WISaVzU3rhf0CguNsuK7WDjqo6OlK8cA0EgKIHVcRYZ9Ya7UWd0YBZkGD6X4rRLro8UVgwvau546xh4y2DQyusQ2WhU28erWcZssM3E7vtVkMeH6H0RiArWmrJ3YgvzAi4BI2bBzCOFeq5QvUDDG/r87aOS0VhQwp23maPaQdUHurLEeMzpGwXAg9XZH5RK/+sS7mzVzjuGkHFPWNTYOVBXXJ+NEIJwDKlzQ4AsdFsg+NXt4dRr3pQf67SOEfJnVeYSJzhdXFQLxrUZ/qQ74qc9OFMZMpjTgsphRZzEOk4qqA93ol5beeI2PC51+dNELa/hOvCu/VkEImROSN5uwxpuGuwRvIuqJ/5ZvI5oZlY+C9IWRqerGWCRIjDL845RO58RlhCpX1k/32BouLyKr7VS8uvrms3bhXRtDek6b+4A6+DGPq0G0x4hN5ALD0b0gazTcUPkq2iESgMhdjEDwcHMejuI94B862aw8MOFSgfhg26rMRqO1WHnefuE57WJXJOQoIll+4bD7WoIv8lx2tIP/3fyT+cDIisQOBZ3tjga5cFFVk6bin7YnhCueT7JTYZMbQ1TNcS0dGtQPITTLA0CoPzJOY5Ndtwy9e3EX/MyWQWfhI2AkCHZwrkqRZuVKaw7asm6FvqMf2pXyuo02MIGlSZnnMqdGxZN80Y/qPHkKpRG8IZGJ+fErQA9ydo/LUswj9OP9SuDMQmgjrnjbdciTX58i9AnubyqilUVLMmMUXjxMwg3GeffPGBAStJomc+EUeGKVqsgCbHfPxDVmjIqbdIJd+hzvlpvBLrv55Hn789W3rMbx7S/0gSgZx0NeOEW/Kpc6oiHSY7eW/8EvMqNJtoODkH98ToEtUCWZNYYudhqHgGU9g23UeYi5cuIYYEiIu3aK6yX1BFWYEKYKPntPXZar5SU1iLWxMFGsjtiPoJsXJptUGxVovT4dQw1Zx0bcYdbTttXMuSHZLS6gJ16os6ne+sBnrFWrsiLMacSdJoBKB/Pnr94svP+5z57UzL8tAIYyvPfdcpo6l7mUaaVb4CX9gTXYxnaDTEbarzHZuG1Zk88jI5WP0y7DOc9lMjJciP+UN8j1rs2XXIam3WzzdxFNkbV15IHd3GuBvRVeB7YnGbX1kX0Pvio9Blj4gXJ4chtJbUHTY1e8Ol8TV6U=)

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

kakao:
  url: https://kapi.kakao.com/v1/user/unlink
  admin-key: ENC(b8lXOQquegCbdIgayVYIDBrhkNeyuucBArJScDGtEA2IWFiWeGUViiDhyZg0XpFE)
