server:
  shutdown: graceful

spring:
  jpa:
    open-in-view: false
    defer-datasource-initialization: false
  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    enabled: true

route:
  vendors:
    - name: odsay
      base-url: https://api.odsay.com/v1/api/searchPubTransPathT
      api-key: ENC(Z0SkQdUTiXWp8kW04EzhajqDndy+TNM/XrQME13n9A9Eog/fxwvICKif2DiiT/8D)
    - name: google
      base-url: https://maps.googleapis.com/maps/api/distancematrix/json
      api-key: ENC(w8KL2jxe1qHrRbQlJcAEybhzDsXoPcNsCpmfChkA251h8oZc5nVjoHta6lIbO6la5novNfz4bpFu3YtDo/X1Z/tKewk3PJhXm8SF3JBRt50=)

auth:
  access-key: ENC(Ve3QKOE7PzbTOpQ6b58Oyi1Qrr9DojPgUA+jCwYcmDdSVdP34Z2eKw==)
  refresh-key: ENC(Ve3QKOE7PzbTOpQ6b58Oyi1Qrr9DojPgUA+jCwYcmDdSVdP34Z2eKw==)
  access-expiration: 7200000
  refresh-expiration: 2419200000

fcm:
  config:
    admin-sdk: ENC(1hTGD9rY8JX+FNQbw+Z2cgjXTXy2/6m0ZCJLIvasQGnl/VseRIHr//aWWPRdH1h/2Ag99MCJl4CTQyNZN3kz5QwE0Ykb/kJ8KHPyPcNOu46Ys2oruYb+pLgsogeqQrmSK1K9szdanWXhsMznoLpnbf8b3V+2SMFo4bokyB1f7aPFu3as66pWhkTySenPn1ipOuIv9r/qsFTm0z5CUKbpPPGJg93AXq9Xs65D8cZqQXXzuDpGtSf9Z2zrBFYV24d38MYSYJuvuhhIdExGXkqO5HcNHYdVkaE2qJLw8bS1XjBvooUJ0SBCCZye2wgbL7r+ufYbGMINuwAXLcWukdB1CUFt2mkWpr7rl6gRqDR0twAd/M5uKUCUupuPBLxzeArutNg2BxG9umJABpozRkG3FCLDcoUhQx1A2Uf0t7BiXdLo0rjzOuy9LsK/wNz5o/4H+XMK188ER+Aemw5a0Hpwlcm498vqMw+lP8GPtjoeIs473JFcdC6uxHjXGYtVHPCQDWwz28dAdQykybvJYA5mV/DXJR0udsAC3YCRvlrHeyNoBNf41i/8xVewu73W7IP4+71CRfwDdiESFd+Ap8HQGUmxT0C/KvhxN/aggYbyDrDhHtOa0Tz1a3B5Ib1CPpNDqTzaIAo9panAfh0G2I0H2xSOCfdmXZi5qBPzMZ6hlzAIaHkkitqIHWlT3prC49CpAjFL6BhdMpY3skYdK9KUv2P+Y7iYcc9R8WQwqpkXzFuiT9nSwClv2HLhsu6epmjXU4CJqIsn1kq67LY6V9FZxidtApd0PjJgehkljXKWKDLxRiD8rLFErPJt84O7tS14b5mXZGeogvhNifAVhNcUyGhLgBvBdqfCn7c6YDvW4Rv975DdJdm1kCfuRQBfONMiYpayYNfOyjtqGnDJMl4m41wYNFxEK9m5KnI8BTVmsqkXy5ZKnWUDOouigujO1EK72XfLXiKocv+5TUdQgL8tRi8riXmbZ+vmzAJt7fYxP8i2stSc1mRUjqgDOOyLo+0xPcSmTdiLPfbNKvIgZ3SP+ZSHc67lX6jcsu7TIo52xqBqUt7HT+IKUljMgziIygD4xUbunHjIUVFYQFpztY4JqjMiU/wepYIbBqaEou379ZF1CqQ9EUGN6N7IHU7tPbviTJevXAPEDddQXbxI9I3zLXGqRVeCKPH7Z4CbJzV6XTpXraZetq7zuO050vFlLI1gs28VlhRhP0Mi+yxsK4Yyorpc3dNJgITDWEhfraPcI2JaOthwoYopnEyJZ/ra2YMCdsDUnHn4ICi2yMHiFu7ZMPy47o03qi4+oLEchs+fdF8hzo2bbZroWp9htzT7gUmFONQxo2/GSAC24THtcEGwWjbigq80lXCcZlP7ou63NQKgPIrhOR/XPB1FV7kvvnL29RNo3QLz2K7Z7rajKFuM5vYFt73fDjfZR7Rv9L+SlhnlJgfOtommSt0Tb/sh4ioco5/uHjic31qeweMWw5iJ6R5YqdkbF3DHwZvrAo8jUuW6JMlA7J1brOU0Is0iyztPXup8hYO8AQSnWqDlOXFCFnBUknpK7Hc89FQTzimIS70lgsW7BlwOI8pA0vma2+ta2cvgw9tKTLkw+C+1oExd1Q3ZR1JoPUnzDprnKdJXifhc0TipFY0CSyKYpWskr0dcRrsYkeftVNJjRtvhCPhZ3g5ZonssQZFbuQmkf10T9GULxhurdOv67wFDBsz0ifXk0s8vmKcLWjun4e8eroA/TF48IwKR5n0F/5vLG6/vcTEumKSF0LnrHKW7gUpXdMFOHOkG/D/aIwrDmtQH37Khv7damGku5On/QPeL2WDicXJIXA2YCflk5EPEGs3oWh21FM3a4J0XJrFaejOlCVS97/lYk3XNJlLjUHCYLVXjggJO6C3N2tVaeIjH58quATVdYqPKNKOjFubFDxWZ0MhaWc+8tDxecZj7EYtrRpB6KVeYxoBhYpls7sKTaTRYkQ8z6QsSQjfAYspe/Es/I746F2jP/v3ALQKV923Lx/qBrtJkOstK+83QSqDZs2jbliYNeTVqO2mvz9QboDsNXGmRrXGlbMpb1ASj32vBevDiDYUQ+wUTrhpcNWbwoVXV+0QRpm2gqvEk0J17kY3Dfk/zxJDmZXreER4y/y9YRSNxR1gJ2aIcuy3P5IW0kYtBU23PfouO3e4e20gO6PNXXBVON3rc/5vI/Hq6DVUrbZhTC36aC5EAcNgc7PhhTnUxbqnzpsEfNVMQu0WkHf9dkm+OMZ4KwmkpKwSctDnc8FafSrr/tme8ObNT+ayXVGUHb2VB1b99LEbQyRW1Su72crxRfMeD6GIt4BIu7eNoKA7f/rfF9i7oesEXnXNFbGhkV+acOxEYaRmouqlq87t3fbWOvqNbSAwU5EQqw9Jxn0oU8uZI4+TXxI7IPKFSs6OZvStVxSPn7LyuYPm6ys4vdsDMw8lqvK9+Zfrn1P05aj2tWJhtNYzMD85815J+/LHJo4okHavW6IH52SYgplkWsXBoVSO2GDBTmJQ8iSK7rjDqFWeXuT/nZ1Qo0W6m5dcZmpces6vgvr0fWD7McXMHC26HiPB3JWC7KHcUOTYFu39z9ErLzp/b6yRHU1xLtUxZpqD0pZ432u3TTR1mVshX2IuvO9yHagbT44n3G1vphavSHNLRsU1ZF1dr2EU0DBB6B3cV8YbNbGaBdG7R0zzgNHat1ueCmcMHZ3CbuH5hR60RT8AnhgfkHRqGszOih6rRlwupqxaZaY70KijEXUoUrJG9sFGpkEoUfa7/I3IUW2pKL38DlwW0oAdusHut+pxZhak/RPw+L5F7bSiB/jtPe0sReOvaezSqgDhFr3kfaKJ5YYjqbLmGszYg19kvqT+lVpQO+XsaHS9uEb1ORSjpa5gepn1D5apqmJr2ZmldISIo0fM8Nv3tUOfGfp4KFaZqo8+TmnuSaGbORKsBOiV/oAWeq3fJRJQsJ4EMruj+Yr+HI7S8Omu9apQ+fLlzvOb6aW13is48B9PzD4c1gAXYjixDW4nQmrcj2IFJJKRgNyQh0lOoOU0Jo6SaMLfIBmbktJ7/vLcuVmzOJKU4sYxb9pTz/XJCCYk/urPJNbNQ30H/dTa0jT/LLa/HMXsZFK4llLsEINv3rSAfYft0hiJWsqWmEWeQ5xSe4xP660CemPi72tupNWt769LNaQZEg9mzdy0H)

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

kakao:
  url: https://kapi.kakao.com/v1/user/unlink
  admin-key: ENC(84d9WaXe+iSolXJ9wIEbJmFEBzeLkgbcP5zkLBRCUJk/Yyic9vwITdVeRArDlFoQ)

management:
  health:
    db:
      enabled: false

api-call:
  page: ENC(Tmip6pkMmuStDTjkRyspLm2PSd5/ov+T9Gzu2XZJKTjmLsrx4dplPIt/8CarbG2B)

allowed-origins:
  api-call: ENC(QicQ16sDQJlHTuf3E/wIS+VBG0UVfQ62HDBXQbtfM8pmnYsBAH8xmACD7PBVgpLjWAHdJXN6bOKv/Z8BZFFbFyfp5x5f7dNCgok83Cn6jSE=)
