name: pull-and-deploy

on:
  workflow_call:
    inputs:
      runner-name:
        type: string
        required: true

env:
  DOCKERHUB_REPOSITORY: ody-official
  DOCKER_CONTAINER_NAME: ody-prod-app

jobs:
  build-and-push:
    runs-on: ${{inputs.runner-name}}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Clean Up Legacy Image And Pull
        run: |
          docker image prune -a -f
          docker pull --platform linux/arm64 ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:${{ github.sha }}-prod

      - name: Set up Container And Run Docker Image
        run: |
          docker stop $DOCKER_CONTAINER_NAME || true
          docker rm $DOCKER_CONTAINER_NAME || true     
          docker run -d --platform linux/arm64 --name $DOCKER_CONTAINER_NAME -v /var/logs/ody-prod-logs:/ody-prod-logs -p 8080:8080 -e SPRING_PROFILES_ACTIVE=prod ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:${{ github.sha }}-prod

      - name: Check Docker Process
        run: docker ps
